---
- hosts: all
  become: true
  tasks: 

  - name: install updates for ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
##########KEYSTONE##################
  - name: install keystone
    apt: 
      name: keystone
      state: present
      update_cache: yes
#########GLANCE###################
  - name: install glance
    apt:
      name: glance
      state: present
      update_cache: yes
  
  - name: start glance
    service:
       name: glance-api
       state: restarted
       enabled: yes
#########NOVA####################
  - name: install nova and prerequisite
    apt:
      name:
        - nova-compute
        - python3-openstackclient
      state: present
      update_cache: yes
 
  - name: start nova
    service:
       name: nova-compute
       state: restarted
       enabled: yes
